// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: invoke.proto

package conformance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstrAcct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Selects an account in an external list
	Index      uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	IsWritable bool   `protobuf:"varint,2,opt,name=is_writable,json=isWritable,proto3" json:"is_writable,omitempty"`
	IsSigner   bool   `protobuf:"varint,3,opt,name=is_signer,json=isSigner,proto3" json:"is_signer,omitempty"`
}

func (x *InstrAcct) Reset() {
	*x = InstrAcct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invoke_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstrAcct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrAcct) ProtoMessage() {}

func (x *InstrAcct) ProtoReflect() protoreflect.Message {
	mi := &file_invoke_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrAcct.ProtoReflect.Descriptor instead.
func (*InstrAcct) Descriptor() ([]byte, []int) {
	return file_invoke_proto_rawDescGZIP(), []int{0}
}

func (x *InstrAcct) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *InstrAcct) GetIsWritable() bool {
	if x != nil {
		return x.IsWritable
	}
	return false
}

func (x *InstrAcct) GetIsSigner() bool {
	if x != nil {
		return x.IsSigner
	}
	return false
}

// The execution context of a program invocation (aka instruction).
// Contains all required information to independently replay an instruction.
// Also includes partial transaction context.
type InstrContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The address of the program invoked.  (32 bytes)
	ProgramId []byte `protobuf:"bytes,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	// Account state accessed by the instruction.  This may include
	// indirect accesses like sysvars.
	Accounts []*AcctState `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	// Account access list for this instruction (refers to above accounts list)
	InstrAccounts []*InstrAcct `protobuf:"bytes,4,rep,name=instr_accounts,json=instrAccounts,proto3" json:"instr_accounts,omitempty"`
	// The input data passed to program execution.
	Data         []byte        `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	CuAvail      uint64        `protobuf:"varint,6,opt,name=cu_avail,json=cuAvail,proto3" json:"cu_avail,omitempty"`
	SlotContext  *SlotContext  `protobuf:"bytes,8,opt,name=slot_context,json=slotContext,proto3" json:"slot_context,omitempty"`
	EpochContext *EpochContext `protobuf:"bytes,9,opt,name=epoch_context,json=epochContext,proto3" json:"epoch_context,omitempty"`
}

func (x *InstrContext) Reset() {
	*x = InstrContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invoke_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstrContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrContext) ProtoMessage() {}

func (x *InstrContext) ProtoReflect() protoreflect.Message {
	mi := &file_invoke_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrContext.ProtoReflect.Descriptor instead.
func (*InstrContext) Descriptor() ([]byte, []int) {
	return file_invoke_proto_rawDescGZIP(), []int{1}
}

func (x *InstrContext) GetProgramId() []byte {
	if x != nil {
		return x.ProgramId
	}
	return nil
}

func (x *InstrContext) GetAccounts() []*AcctState {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *InstrContext) GetInstrAccounts() []*InstrAcct {
	if x != nil {
		return x.InstrAccounts
	}
	return nil
}

func (x *InstrContext) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InstrContext) GetCuAvail() uint64 {
	if x != nil {
		return x.CuAvail
	}
	return 0
}

func (x *InstrContext) GetSlotContext() *SlotContext {
	if x != nil {
		return x.SlotContext
	}
	return nil
}

func (x *InstrContext) GetEpochContext() *EpochContext {
	if x != nil {
		return x.EpochContext
	}
	return nil
}

// The results of executing an InstrContext.
type InstrEffects struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// result is zero if the instruction executed succesfully.
	// Otherwise, a non-zero error code.  Error codes are not relevant to
	// consensus.
	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	// Some error cases additionally have a custom error code.  Unlike
	// the expected_result, this is stable across clients.
	CustomErr uint32 `protobuf:"varint,2,opt,name=custom_err,json=customErr,proto3" json:"custom_err,omitempty"`
	// Copies of accounts that were changed.  May be in an arbitrary
	// order.  The pubkey of each account is unique in this list.  Each
	// account address modified here must also be in the
	// InstrContext.
	ModifiedAccounts []*AcctState `protobuf:"bytes,3,rep,name=modified_accounts,json=modifiedAccounts,proto3" json:"modified_accounts,omitempty"`
	CuAvail          uint64       `protobuf:"varint,4,opt,name=cu_avail,json=cuAvail,proto3" json:"cu_avail,omitempty"`
	// Instruction return data.
	ReturnData []byte `protobuf:"bytes,5,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
}

func (x *InstrEffects) Reset() {
	*x = InstrEffects{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invoke_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstrEffects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrEffects) ProtoMessage() {}

func (x *InstrEffects) ProtoReflect() protoreflect.Message {
	mi := &file_invoke_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrEffects.ProtoReflect.Descriptor instead.
func (*InstrEffects) Descriptor() ([]byte, []int) {
	return file_invoke_proto_rawDescGZIP(), []int{2}
}

func (x *InstrEffects) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *InstrEffects) GetCustomErr() uint32 {
	if x != nil {
		return x.CustomErr
	}
	return 0
}

func (x *InstrEffects) GetModifiedAccounts() []*AcctState {
	if x != nil {
		return x.ModifiedAccounts
	}
	return nil
}

func (x *InstrEffects) GetCuAvail() uint64 {
	if x != nil {
		return x.CuAvail
	}
	return 0
}

func (x *InstrEffects) GetReturnData() []byte {
	if x != nil {
		return x.ReturnData
	}
	return nil
}

// An instruction processing test fixture.
type InstrFixture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input  *InstrContext `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Output *InstrEffects `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *InstrFixture) Reset() {
	*x = InstrFixture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invoke_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstrFixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrFixture) ProtoMessage() {}

func (x *InstrFixture) ProtoReflect() protoreflect.Message {
	mi := &file_invoke_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrFixture.ProtoReflect.Descriptor instead.
func (*InstrFixture) Descriptor() ([]byte, []int) {
	return file_invoke_proto_rawDescGZIP(), []int{3}
}

func (x *InstrFixture) GetInput() *InstrContext {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *InstrFixture) GetOutput() *InstrEffects {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_invoke_proto protoreflect.FileDescriptor

var file_invoke_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x2e, 0x73, 0x65, 0x61, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x09, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x41, 0x63,
	0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x77,
	0x72, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69,
	0x73, 0x57, 0x72, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73,
	0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x22, 0xf8, 0x02, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x72,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x73,
	0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x2e, 0x73, 0x65, 0x61, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x63, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x08, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x48, 0x0a, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x5f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x2e, 0x73, 0x65, 0x61, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x41, 0x63, 0x63, 0x74,
	0x52, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x75, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63, 0x75, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x12, 0x46,
	0x0a, 0x0c, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6f, 0x6c, 0x61, 0x6e,
	0x61, 0x2e, 0x73, 0x65, 0x61, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6c,
	0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x0b, 0x73, 0x6c, 0x6f, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x49, 0x0a, 0x0d, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x2e, 0x73, 0x65, 0x61, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x52, 0x0c, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x22, 0xd1, 0x01, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x72, 0x72, 0x12, 0x4e, 0x0a, 0x11, 0x6d, 0x6f, 0x64,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6f, 0x6c, 0x61, 0x6e,
	0x61, 0x2e, 0x73, 0x65, 0x61, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63,
	0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x10, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x75, 0x5f,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63, 0x75, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x88, 0x01, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x46,
	0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x12, 0x3a, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6f, 0x6c, 0x61,
	0x6e, 0x61, 0x2e, 0x73, 0x65, 0x61, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x6e, 0x73, 0x74, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x05, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x12, 0x3c, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x2e,
	0x73, 0x65, 0x61, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74,
	0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_invoke_proto_rawDescOnce sync.Once
	file_invoke_proto_rawDescData = file_invoke_proto_rawDesc
)

func file_invoke_proto_rawDescGZIP() []byte {
	file_invoke_proto_rawDescOnce.Do(func() {
		file_invoke_proto_rawDescData = protoimpl.X.CompressGZIP(file_invoke_proto_rawDescData)
	})
	return file_invoke_proto_rawDescData
}

var file_invoke_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_invoke_proto_goTypes = []any{
	(*InstrAcct)(nil),    // 0: org.solana.sealevel.v1.InstrAcct
	(*InstrContext)(nil), // 1: org.solana.sealevel.v1.InstrContext
	(*InstrEffects)(nil), // 2: org.solana.sealevel.v1.InstrEffects
	(*InstrFixture)(nil), // 3: org.solana.sealevel.v1.InstrFixture
	(*AcctState)(nil),    // 4: org.solana.sealevel.v1.AcctState
	(*SlotContext)(nil),  // 5: org.solana.sealevel.v1.SlotContext
	(*EpochContext)(nil), // 6: org.solana.sealevel.v1.EpochContext
}
var file_invoke_proto_depIdxs = []int32{
	4, // 0: org.solana.sealevel.v1.InstrContext.accounts:type_name -> org.solana.sealevel.v1.AcctState
	0, // 1: org.solana.sealevel.v1.InstrContext.instr_accounts:type_name -> org.solana.sealevel.v1.InstrAcct
	5, // 2: org.solana.sealevel.v1.InstrContext.slot_context:type_name -> org.solana.sealevel.v1.SlotContext
	6, // 3: org.solana.sealevel.v1.InstrContext.epoch_context:type_name -> org.solana.sealevel.v1.EpochContext
	4, // 4: org.solana.sealevel.v1.InstrEffects.modified_accounts:type_name -> org.solana.sealevel.v1.AcctState
	1, // 5: org.solana.sealevel.v1.InstrFixture.input:type_name -> org.solana.sealevel.v1.InstrContext
	2, // 6: org.solana.sealevel.v1.InstrFixture.output:type_name -> org.solana.sealevel.v1.InstrEffects
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_invoke_proto_init() }
func file_invoke_proto_init() {
	if File_invoke_proto != nil {
		return
	}
	file_context_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_invoke_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*InstrAcct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invoke_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*InstrContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invoke_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*InstrEffects); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invoke_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*InstrFixture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_invoke_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invoke_proto_goTypes,
		DependencyIndexes: file_invoke_proto_depIdxs,
		MessageInfos:      file_invoke_proto_msgTypes,
	}.Build()
	File_invoke_proto = out.File
	file_invoke_proto_rawDesc = nil
	file_invoke_proto_goTypes = nil
	file_invoke_proto_depIdxs = nil
}
