// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: serialize.proto

package conformance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VmMemRegion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VmAddr     uint64 `protobuf:"varint,1,opt,name=vm_addr,json=vmAddr,proto3" json:"vm_addr,omitempty"`
	Content    []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	IsWritable bool   `protobuf:"varint,3,opt,name=is_writable,json=isWritable,proto3" json:"is_writable,omitempty"`
}

func (x *VmMemRegion) Reset() {
	*x = VmMemRegion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serialize_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmMemRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmMemRegion) ProtoMessage() {}

func (x *VmMemRegion) ProtoReflect() protoreflect.Message {
	mi := &file_serialize_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmMemRegion.ProtoReflect.Descriptor instead.
func (*VmMemRegion) Descriptor() ([]byte, []int) {
	return file_serialize_proto_rawDescGZIP(), []int{0}
}

func (x *VmMemRegion) GetVmAddr() uint64 {
	if x != nil {
		return x.VmAddr
	}
	return 0
}

func (x *VmMemRegion) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *VmMemRegion) GetIsWritable() bool {
	if x != nil {
		return x.IsWritable
	}
	return false
}

type InstrSerializeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  int32          `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Regions []*VmMemRegion `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
}

func (x *InstrSerializeResult) Reset() {
	*x = InstrSerializeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serialize_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstrSerializeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrSerializeResult) ProtoMessage() {}

func (x *InstrSerializeResult) ProtoReflect() protoreflect.Message {
	mi := &file_serialize_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrSerializeResult.ProtoReflect.Descriptor instead.
func (*InstrSerializeResult) Descriptor() ([]byte, []int) {
	return file_serialize_proto_rawDescGZIP(), []int{1}
}

func (x *InstrSerializeResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *InstrSerializeResult) GetRegions() []*VmMemRegion {
	if x != nil {
		return x.Regions
	}
	return nil
}

var File_serialize_proto protoreflect.FileDescriptor

var file_serialize_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x16, 0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x2e, 0x73, 0x65,
	0x61, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x61, 0x0a, 0x0b, 0x56, 0x6d, 0x4d,
	0x65, 0x6d, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x6d, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x76, 0x6d, 0x41, 0x64, 0x64,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69,
	0x73, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x69, 0x73, 0x57, 0x72, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x6d, 0x0a, 0x14,
	0x49, 0x6e, 0x73, 0x74, 0x72, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3d, 0x0a, 0x07,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x6f, 0x72, 0x67, 0x2e, 0x73, 0x6f, 0x6c, 0x61, 0x6e, 0x61, 0x2e, 0x73, 0x65, 0x61, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x6d, 0x4d, 0x65, 0x6d, 0x52, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x52, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x2e,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serialize_proto_rawDescOnce sync.Once
	file_serialize_proto_rawDescData = file_serialize_proto_rawDesc
)

func file_serialize_proto_rawDescGZIP() []byte {
	file_serialize_proto_rawDescOnce.Do(func() {
		file_serialize_proto_rawDescData = protoimpl.X.CompressGZIP(file_serialize_proto_rawDescData)
	})
	return file_serialize_proto_rawDescData
}

var file_serialize_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_serialize_proto_goTypes = []any{
	(*VmMemRegion)(nil),          // 0: org.solana.sealevel.v1.VmMemRegion
	(*InstrSerializeResult)(nil), // 1: org.solana.sealevel.v1.InstrSerializeResult
}
var file_serialize_proto_depIdxs = []int32{
	0, // 0: org.solana.sealevel.v1.InstrSerializeResult.regions:type_name -> org.solana.sealevel.v1.VmMemRegion
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_serialize_proto_init() }
func file_serialize_proto_init() {
	if File_serialize_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serialize_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*VmMemRegion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serialize_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*InstrSerializeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serialize_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_serialize_proto_goTypes,
		DependencyIndexes: file_serialize_proto_depIdxs,
		MessageInfos:      file_serialize_proto_msgTypes,
	}.Build()
	File_serialize_proto = out.File
	file_serialize_proto_rawDesc = nil
	file_serialize_proto_goTypes = nil
	file_serialize_proto_depIdxs = nil
}
